// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: example/proto/hellnet/events/v1/stock.proto

package hellnet_events_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Reserved      int32                  `protobuf:"varint,3,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Available     int32                  `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	WarehouseId   string                 `protobuf:"bytes,5,opt,name=warehouseId,proto3" json:"warehouseId,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockUpdated) Reset() {
	*x = StockUpdated{}
	mi := &file_example_proto_hellnet_events_v1_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockUpdated) ProtoMessage() {}

func (x *StockUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_hellnet_events_v1_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockUpdated.ProtoReflect.Descriptor instead.
func (*StockUpdated) Descriptor() ([]byte, []int) {
	return file_example_proto_hellnet_events_v1_stock_proto_rawDescGZIP(), []int{0}
}

func (x *StockUpdated) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockUpdated) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockUpdated) GetReserved() int32 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

func (x *StockUpdated) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *StockUpdated) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *StockUpdated) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_example_proto_hellnet_events_v1_stock_proto protoreflect.FileDescriptor

const file_example_proto_hellnet_events_v1_stock_proto_rawDesc = "" +
	"\n" +
	"+example/proto/hellnet/events/v1/stock.proto\x12\x11hellnet.events.v1\"\xc2\x01\n" +
	"\fStockUpdated\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1a\n" +
	"\breserved\x18\x03 \x01(\x05R\breserved\x12\x1c\n" +
	"\tavailable\x18\x04 \x01(\x05R\tavailable\x12 \n" +
	"\vwarehouseId\x18\x05 \x01(\tR\vwarehouseId\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestampBtZ^github.com/guilhermelinosp/hellnet-lib-kafka/example/proto/hellnet/events/v1;hellnet_events_v1\xaa\x02\x11Hellnet.Events.V1b\x06proto3"

var (
	file_example_proto_hellnet_events_v1_stock_proto_rawDescOnce sync.Once
	file_example_proto_hellnet_events_v1_stock_proto_rawDescData []byte
)

func file_example_proto_hellnet_events_v1_stock_proto_rawDescGZIP() []byte {
	file_example_proto_hellnet_events_v1_stock_proto_rawDescOnce.Do(func() {
		file_example_proto_hellnet_events_v1_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_proto_hellnet_events_v1_stock_proto_rawDesc), len(file_example_proto_hellnet_events_v1_stock_proto_rawDesc)))
	})
	return file_example_proto_hellnet_events_v1_stock_proto_rawDescData
}

var file_example_proto_hellnet_events_v1_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_example_proto_hellnet_events_v1_stock_proto_goTypes = []any{
	(*StockUpdated)(nil), // 0: hellnet.events.v1.StockUpdated
}
var file_example_proto_hellnet_events_v1_stock_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_proto_hellnet_events_v1_stock_proto_init() }
func file_example_proto_hellnet_events_v1_stock_proto_init() {
	if File_example_proto_hellnet_events_v1_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_proto_hellnet_events_v1_stock_proto_rawDesc), len(file_example_proto_hellnet_events_v1_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_proto_hellnet_events_v1_stock_proto_goTypes,
		DependencyIndexes: file_example_proto_hellnet_events_v1_stock_proto_depIdxs,
		MessageInfos:      file_example_proto_hellnet_events_v1_stock_proto_msgTypes,
	}.Build()
	File_example_proto_hellnet_events_v1_stock_proto = out.File
	file_example_proto_hellnet_events_v1_stock_proto_goTypes = nil
	file_example_proto_hellnet_events_v1_stock_proto_depIdxs = nil
}
